<a href="https://colab.research.google.com/github/Nikitaion/TensorFlowLearning/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Tensors

In [ ]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
print("TensorFlow version: " + tf.__version__)
print("\nIs GPU Enabled:")
!nvidia-smi

TensorFlow version: 2.6.0

Is GPU Enabled:
Fri Nov  5 09:49:52 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   35C    P8    28W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                             

In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of the tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10,7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create matrix with another datatype
another_matrix = tf.constant([[10.,7.],
                              [7., 10.],
                              [12.,23.]], dtype = tf.float16) # specify datatype with dtype
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [12., 23.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[5, 6, 7], [4, 2, 8]], 
                      [[12, 41, 2], [9, 6 , 4]],
                      [[12, 2, 4], [ 4, 13, 4]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 5,  6,  7],
        [ 4,  2,  8]],

       [[12, 41,  2],
        [ 9,  6,  4]],

       [[12,  2,  4],
        [ 4, 13,  4]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# What we have created so far
* Scalar - single number
* Vector - number with direction (e.g. wind speed and direction)
* Matrix - 2-dimensional array of numbers
* Tensor - n-dimentional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a Vector...)

### Creating Tensors with a `tf.Variable`

In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try to change one element in changeable tensor
changeable_tensor[0] = 7
changeable_tensor

In [ ]:
# How about we try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

In [ ]:
# Let's try to change one element in unchangeable_tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

### Creating random tensors
Random tensors are tensors with some arbitrary size which contain random numbers.

In [ ]:
# Create 2 random (but the same) tensors
random1 = tf.random.Generator.from_seed(42) # set seed for reproducibility
random2 = tf.random.Generator.from_seed(42)
random1, random2

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7f72eb25d490>,
 <tensorflow.python.ops.stateful_random_ops.Generator at 0x7f72eb25dfd0>)

In [ ]:
# Fill
random1 = random1.normal(shape=(3,2))
random2 = random2.normal(shape=(3,2))
# Are they equal?
random1, random2, random1 == random2
# Yes - because seeds equal

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

### Shuffle the order of elements in a tensor


In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data. So the inherent order doesn't affect learning.)
not_shuffled = tf.constant([[10, 7], 
                           [3, 4], 
                           [2, 5]])
not_shuffled.ndim

2

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# shuffle our not shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.08029842], shape=(1,), dtype=float32)
tf.Tensor([0.65728486], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(42)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(42)
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))
print(tf.random.uniform([1]))

tf.Tensor([0.6645621], shape=(1,), dtype=float32)
tf.Tensor([0.68789124], shape=(1,), dtype=float32)
tf.Tensor([0.7413678], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(1234)

@tf.function
def f():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b

@tf.function
def g():
  в = tf.random.uniform([1])
  с = tf.random.uniform([1])
  return с, в

print(f())  # prints '(A1, A2)'
print(g())  # prints '(A1, A2)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.1689806], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.13047123], dtype=float32)>)


In [ ]:
tf.random.set_seed(42)
print(tf.random.uniform([1], seed=1))  
print(tf.random.uniform([1], seed=1))

tf.Tensor([0.15012848], shape=(1,), dtype=float32)
tf.Tensor([0.11101711], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(42)
print(tf.random.uniform([1], seed=1))  
print(tf.random.uniform([1], seed=1))

tf.Tensor([0.15012848], shape=(1,), dtype=float32)
tf.Tensor([0.11101711], shape=(1,), dtype=float32)


In [ ]:
tf.random.set_seed(42)
print(tf.random.uniform([1], seed=1))  
print(tf.random.uniform([1], seed=1))

tf.Tensor([0.15012848], shape=(1,), dtype=float32)
tf.Tensor([0.11101711], shape=(1,), dtype=float32)


In [ ]:
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8354591], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.46399975], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>)


In [ ]:
tf.random.set_seed(42)
@tf.function
def foo():
  a = tf.random.uniform([1], seed=1)
  b = tf.random.uniform([1], seed=1)
  return a, b
print(foo())  # prints '(A1, A1)'
print(foo())  # prints '(A2, A2)'

print('bar')
@tf.function
def bar():
  a = tf.random.uniform([1])
  b = tf.random.uniform([1])
  return a, b
print(bar())  # prints '(A1, A2)'
print(bar())  # prints '(A3, A4)'

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>)
bar
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.8354591], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.15012848], dtype=float32)>)
(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.46399975], dtype=float32)>, <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.11101711], dtype=float32)>)


### Other ways to make tensors

In [ ]:
# Create a tensor with all ones(1)
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor with all zeros
tf.zeros([4, 3])

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
# Or 
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into Tensors
The main differense between NumPy and arrays Tensorflow tensors is that tensors can be run on GPU (much faster fur numerical computing)

In [ ]:
# You can also turn NumPy arrays into Tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype = np.int32) # create a Numpy array between 1 and 25
numpy_A

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A)
A

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
B = tf.constant(numpy_A, shape = (2, 3, 4)) # Shape should be equal array.length
B

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
C = tf.constant(numpy_A, shape = (3, 8)) # Shape should be equal array.length
C

<tf.Tensor: shape=(3, 8), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>

In [ ]:
A.ndim, B.ndim, C.ndim

(1, 3, 2)

### Getting information from tensors

When dealing with tensors, you probably want to be aware of the following attributes:
* Shape
* Rank - number of dimensions (.ndim)
* Axis or dimension
* Size - number of elements in a tensor

In [ ]:
# Create a rank 4 tensor(4 dimensions)
rank_4_tensor = tf.zeros(shape = [2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of  every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along 0 axis:", rank_4_tensor.shape[0])
print("Elements along last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of  every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements along last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors

Tensors can be indexed just like Python lists

In [ ]:
some_list = [1, 2, 3, 4]
some_list[:2]

[1, 2]

In [ ]:
# Get the first two elements of each dimension in our tensor. 
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get first element from each dimension from each index, except for the final one
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Get first element from each dimension from each index, except for the penultimate(предпоследний)
rank_4_tensor[:1, :1, :, :1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension onto our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis = 0) # expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis = 1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

### Manipulating tensors (tensors operations)

**Basic operations**

`+`,`-`,`*`,`/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
# tensor built-in multiply
tf.multiply(tensor, 20)
# built-in operations are faster

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[200, 140],
       [ 60,  80]], dtype=int32)>

**Matrix multiplication**

In machine learning, matrix multiplication is one of the most common tensor operations.

In [ ]:
# Matrix multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix multiplication with python operator '@'
# tensor * tensor - it is a wrong way
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
/

()

**The dot product**

Matrix multiplication is also referred to as the dot product, and now you can perform matrix multiplication using:
* `tf.matmul()`
* `tf.tensordot()`

Generally when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors. To satisfy the matrix multiplication rules

In [ ]:
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
X, Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
tf.transpose(X), tf.reshape(X, shape=(2,3)), tf.reshape(X, shape=(3,2))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>)

In [ ]:
# Perform the dot product on X and Y (requires X or Y to be transposed)
# Transposing results in a different outputh than reshaping
tf.tensordot(tf.transpose(X), Y, axes=1) # tensordot - for matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.tensordot(X, tf.transpose(Y), axes=1) # tensordot - for matrix multiplication

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (transposed)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(X), Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between X and Y (reshaped)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# Check the values of Y, reshape Y and transposed Y
print("Normal Y:")
print(Y, "\n")

print("Y reshaped to (2,3)")
print(tf.reshape(Y, shape=(2,3)), "\n")

print("Y transposed:")
print(tf.transpose(Y))

Normal Y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

Y reshaped to (2,3)
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

Y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


## Generally when performing matrix multiplication on two tensors and one of the axes doesn't line up, you will transpose (rather than reshape) one of the tensors. To satisfy the matrix multiplication rules

# Changing the datatype of tensors

In [ ]:
# Create tensor with default dt
B = tf.constant([1.7, 7.4])
B, B.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.7, 7.4], dtype=float32)>,
 tf.float32)

In [ ]:
C = tf.constant([7, 10])
C.dtype

tf.int32

In [ ]:
# Changing from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
# Changing from int32 to float32
E = tf.cast(C, dtype=tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [ ]:
E_float16 = tf.cast(C, dtype=tf.float16)
E_float16, E_float16.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>,
 tf.float16)

### Aggregating tensors

In [ ]:
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# Get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* get the minimum 
* get the maximum
* get the mean of the tensor
* get the sum of the tensor

In [ ]:
# Create random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0., 100., size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([ 1, 38, 13, 45, 76, 78, 71, 19,  7, 38, 60, 81, 85, 98, 31, 82, 25,
       75, 15,  5, 66, 15, 51, 83, 98, 39, 52, 81, 11, 85, 65, 27,  8, 49,
       94, 71, 31, 27, 83, 52, 95, 71, 73, 85, 60, 19,  2, 17, 41, 65])>

In [ ]:
tf.math.reduce_min(E), tf.math.reduce_max(E), tf.math.reduce_mean(E),  tf.math.reduce_min(E), tf.math.reduce_sum(E)


(<tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=98>,
 <tf.Tensor: shape=(), dtype=int64, numpy=51>,
 <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2559>)

In [ ]:
# Find the variance (2 variants)
tfp.stats.variance(E), tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))

(<tf.Tensor: shape=(), dtype=int64, numpy=875>,
 <tf.Tensor: shape=(), dtype=float32, numpy=875.3077>)

In [ ]:
# Find the standart deviation (need float32/float64)
X = tf.cast(E, dtype=tf.float32)
tf.math.reduce_std(X)

<tf.Tensor: shape=(), dtype=float32, numpy=29.5856>

### Find the positional maximum and minimum of the tensor

In [ ]:
# argmax returns index of maximum value across axes of a tensor
tf.math.argmax(E)

<tf.Tensor: shape=(), dtype=int64, numpy=13>

In [ ]:
# argmax returns index of minimum value across axes of a tensor
tf.math.argmin(E)

<tf.Tensor: shape=(), dtype=int64, numpy=0>

<tf.Tensor: shape=(), dtype=float32, numpy=875.3077>

In [ ]:
# Create a new tensor for finding positional min/max
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
tf.math.argmax(F), tf.math.argmin(F)

(<tf.Tensor: shape=(), dtype=int64, numpy=42>,
 <tf.Tensor: shape=(), dtype=int64, numpy=16>)

In [ ]:
# Index on our langest/smallest value position
F[tf.argmax(F)], F[tf.argmin(F)]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [ ]:
# Chect for equality
assert F[tf.argmax(F)] == tf.reduce_max(F)
# If no error - ok

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

### One-hot encoding tensor

In [ ]:
# Createa list of indices
some_list = [0, 1, 2, 3] # cold be red, yellow, green and blue
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="lol", off_value="kek")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'lol', b'kek', b'kek', b'kek'],
       [b'kek', b'lol', b'kek', b'kek'],
       [b'kek', b'kek', b'lol', b'kek'],
       [b'kek', b'kek', b'kek', b'lol']], dtype=object)>

### Tensors and NumPy
Tensorflow interacts beautifully wuth NumPy arrays

We can convert tensor into NumPy array and vice versa

One of the main difference between TensorFlow tensor and NumPy array - is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing)

In [ ]:
# Create tensor directly from numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J to numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# The default type of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Wed Nov  3 17:17:24 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 495.44       Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P8    35W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

** Note: ** If you have access on CUDA-enabled GPU, TwnsorFlow will automatically use it whenever possible

### Homework

In [ ]:
# Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
vector = tf.constant([2, 6, 12])
scalar = tf.constant(3)
matrix = tf.constant([[1, 2, 3],
                      [4, 5, 6]])
tensor = tf.constant([[[1, 2, 3], 
                       [4, 5, 6],],
                      [[7, 8, 9], 
                       [10, 11, 12]]])
vector, scalar, matrix, tensor

(<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  6, 12], dtype=int32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=int32)>)

In [ ]:
# Find the shape, rank and size of the tensors you created in 1.
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([3]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=3>)

In [ ]:
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [ ]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 3]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=6>)

In [ ]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([2, 2, 3]), 3, <tf.Tensor: shape=(), dtype=int32, numpy=12>)

In [ ]:
# Create two tensors containing random values between 0 and 1 with shape [5, 300].
tensor_one = tf.constant(tf.random.uniform(shape=[5, 300]))
tensor_two = tf.constant(tf.random.uniform(shape=[1500]), shape=(5, 300))
tensor_one

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.20952594, 0.07946479, 0.8939941 , ..., 0.5821004 , 0.93130744,
        0.7368045 ],
       [0.8911463 , 0.465603  , 0.9812691 , ..., 0.5063453 , 0.82892954,
        0.41618717],
       [0.3814733 , 0.18006349, 0.1667993 , ..., 0.16662753, 0.50133   ,
        0.917305  ],
       [0.9071454 , 0.87995994, 0.6858367 , ..., 0.74011827, 0.2618233 ,
        0.11815202],
       [0.97781765, 0.39648616, 0.6741847 , ..., 0.74597204, 0.41781032,
        0.93752015]], dtype=float32)>

In [ ]:
tensor_one.shape, tensor_one.ndim, tf.size(tensor_one)

(TensorShape([5, 300]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=1500>)

In [ ]:
tensor_two.shape, tensor_two.ndim, tf.size(tensor_two)

(TensorShape([5, 300]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=1500>)

In [ ]:
# Multiply the two tensors you created in previous step using matrix multiplication.
tf.matmul(tensor_one, tf.transpose(tensor_two))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.936264, 77.98968 , 72.27736 , 74.28462 , 74.86198 ],
       [73.432884, 79.44583 , 74.420845, 75.073784, 79.244354],
       [76.88106 , 76.58536 , 76.16366 , 77.77385 , 76.74028 ],
       [76.5078  , 77.813965, 71.99458 , 77.09352 , 77.61808 ],
       [78.82603 , 82.06985 , 75.500114, 79.598694, 79.46073 ]],
      dtype=float32)>

In [ ]:
# Multiply the two tensors you created in previous step using dot product
tf.tensordot(tensor_one, tf.transpose(tensor_two), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[75.936264, 77.98968 , 72.27736 , 74.28462 , 74.86198 ],
       [73.432884, 79.44583 , 74.420845, 75.073784, 79.244354],
       [76.88106 , 76.58536 , 76.16366 , 77.77385 , 76.74028 ],
       [76.5078  , 77.813965, 71.99458 , 77.09352 , 77.61808 ],
       [78.82603 , 82.06985 , 75.500114, 79.598694, 79.46073 ]],
      dtype=float32)>

In [ ]:
# Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
tensor = tf.constant(tf.random.uniform(shape=[224, 224, 3]))
tensor

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.19281638, 0.6706935 , 0.47679496],
        [0.5697421 , 0.39761853, 0.18175268],
        [0.6677712 , 0.48115647, 0.8118266 ],
        ...,
        [0.46452808, 0.45868945, 0.9631299 ],
        [0.8764913 , 0.09501743, 0.30889595],
        [0.8839221 , 0.30176234, 0.7539103 ]],

       [[0.6376561 , 0.14313066, 0.8463055 ],
        [0.66305375, 0.5555774 , 0.24638951],
        [0.48808646, 0.36936498, 0.11277127],
        ...,
        [0.6213269 , 0.33207035, 0.7121198 ],
        [0.51567554, 0.67524517, 0.4759394 ],
        [0.1218152 , 0.47727144, 0.22320807]],

       [[0.96623325, 0.4000361 , 0.24714744],
        [0.6222594 , 0.69294584, 0.81901634],
        [0.14200008, 0.58572245, 0.7704307 ],
        ...,
        [0.55206776, 0.0915792 , 0.27293158],
        [0.30323994, 0.5618496 , 0.3933885 ],
        [0.4120767 , 0.500301  , 0.5386454 ]],

       ...,

       [[0.89593005, 0.5388367 , 0.94294584],
        [0.12

In [ ]:
# Find the min and max values of the tensor you created in 6 along the first axis.
tf.reduce_min(tf.reduce_min(tensor, axis=0))

<tf.Tensor: shape=(), dtype=float32, numpy=4.6491623e-06>

In [ ]:
tf.reduce_max(tf.reduce_max(tensor, axis=0))

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999785>

In [ ]:
# Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
tensor_shape = tf.constant(tf.random.uniform(shape=[1, 224, 224, 3]))
tensor_shape.shape

TensorShape([1, 224, 224, 3])

In [ ]:
tensor_shape_squeezed = tf.squeeze(tensor_shape)
tensor_shape_squeezed, tensor_shape_squeezed.shape

(<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
 array([[[0.05225003, 0.50963247, 0.8090826 ],
         [0.6840806 , 0.8174261 , 0.6544466 ],
         [0.6597632 , 0.54885256, 0.41981626],
         ...,
         [0.14845169, 0.80303776, 0.9925443 ],
         [0.5891669 , 0.8755958 , 0.9322274 ],
         [0.61256874, 0.92286897, 0.8401011 ]],
 
        [[0.5237982 , 0.77908957, 0.94906175],
         [0.00167477, 0.8422941 , 0.2815857 ],
         [0.7331481 , 0.05240119, 0.39540422],
         ...,
         [0.14826119, 0.6558224 , 0.06122565],
         [0.7335422 , 0.0345124 , 0.51267827],
         [0.61119616, 0.92972267, 0.60142326]],
 
        [[0.40670323, 0.02215338, 0.26072776],
         [0.42260337, 0.4068904 , 0.29605615],
         [0.95271945, 0.03167808, 0.12544906],
         ...,
         [0.6702367 , 0.20522463, 0.38573062],
         [0.60199964, 0.2050283 , 0.82260394],
         [0.9687164 , 0.12225616, 0.54375434]],
 
        ...,
 
        [[0.29435468, 0.7408123 

In [ ]:
# Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
some_list = [9,8,7,6,5,4,3,2,1,0] # cold be red, yellow, green and blue
tf.argmax(some_list)


<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
#One-hot encode the tensor you created
tf.one_hot(some_list, depth=10, on_value="lol", off_value="kek")

<tf.Tensor: shape=(10, 10), dtype=string, numpy=
array([[b'kek', b'kek', b'kek', b'kek', b'kek', b'kek', b'kek', b'kek',
        b'kek', b'lol'],
       [b'kek', b'kek', b'kek', b'kek', b'kek', b'kek', b'kek', b'kek',
        b'lol', b'kek'],
       [b'kek', b'kek', b'kek', b'kek', b'kek', b'kek', b'kek', b'lol',
        b'kek', b'kek'],
       [b'kek', b'kek', b'kek', b'kek', b'kek', b'kek', b'lol', b'kek',
        b'kek', b'kek'],
       [b'kek', b'kek', b'kek', b'kek', b'kek', b'lol', b'kek', b'kek',
        b'kek', b'kek'],
       [b'kek', b'kek', b'kek', b'kek', b'lol', b'kek', b'kek', b'kek',
        b'kek', b'kek'],
       [b'kek', b'kek', b'kek', b'lol', b'kek', b'kek', b'kek', b'kek',
        b'kek', b'kek'],
       [b'kek', b'kek', b'lol', b'kek', b'kek', b'kek', b'kek', b'kek',
        b'kek', b'kek'],
       [b'kek', b'lol', b'kek', b'kek', b'kek', b'kek', b'kek', b'kek',
        b'kek', b'kek'],
       [b'lol', b'kek', b'kek', b'kek', b'kek', b'kek', b'kek', b'kek',
      

## TF guide for begginers
### https://www.tensorflow.org/tutorials/quickstart/beginner

In [ ]:
# Load and prepare the MNIST dataset. Convert the sample data from integers to floating-point numbers:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train.dtype, x_train.shape, x_train.ndim, tf.size(x_train)

(dtype('uint8'),
 (60000, 28, 28),
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=47040000>)

In [ ]:
x_train, x_test = x_train / 255.0, x_test / 255.0
x_train.dtype, x_train.shape, x_train.ndim, tf.size(x_train)

(dtype('float64'),
 (60000, 28, 28),
 3,
 <tf.Tensor: shape=(), dtype=int32, numpy=47040000>)

In [ ]:
# Build a tf.keras.Sequential model by stacking layers.
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
# For each example, the model returns a vector of logits or log-odds scores, one for each class.
predictions = model(x_train[:1]).numpy()
predictions

array([[ 7.7191776e-01,  5.1497626e-01,  6.4517426e-01,  9.6985698e-04,
        -1.0242006e+00,  1.5634874e-01, -6.8326727e-02, -7.4702486e-02,
         3.5353923e-01, -1.3860989e-01]], dtype=float32)

In [ ]:
# The tf.nn.softmax function converts these logits to probabilities for each class:
tf.nn.softmax(predictions).numpy()

array([[0.17409123, 0.13464451, 0.15336734, 0.08053014, 0.02888901,
        0.0940673 , 0.07513865, 0.07466111, 0.11457172, 0.07003897]],
      dtype=float32)

In [ ]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy, which takes a vector of logits and a True index and returns a scalar loss for each example.
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn

In [ ]:
# This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.
#This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3.
loss_fn(y_train[:1], predictions).numpy()

2.3637447

In [ ]:
# Before you start training, configure and compile the model using Keras Model.compile. 
# Set the optimizer class to adam, set the loss to the loss_fn function you defined earlier, 
# and specify a metric to be evaluated for the model by setting the metrics parameter to accuracy.
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])
model

In [ ]:
# Train and evaluate your model

# Use the Model.fit method to adjust your model parameters and minimize the loss:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2955 - accuracy: 0.9143
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1432 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1064 - accuracy: 0.9679
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0873 - accuracy: 0.9729
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0757 - accuracy: 0.9762


In [ ]:
# The Model.evaluate method checks the models performance, usually on a "Validation-set" or "Test-set".
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0723 - accuracy: 0.9776


[0.07225031405687332, 0.9775999784469604]

In [ ]:
# The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the TensorFlow tutorials.
# If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.9739712e-08, 1.9290118e-09, 5.2766874e-05, 3.9003811e-05,
        2.8803133e-11, 3.4952888e-07, 2.7125603e-13, 9.9990225e-01,
        3.8122003e-08, 5.6088384e-06],
       [7.8710380e-09, 6.4175903e-05, 9.9992394e-01, 9.5587220e-06,
        3.1974123e-16, 2.3885596e-06, 4.4646550e-10, 7.5021308e-14,
        2.2921641e-08, 2.1066497e-14],
       [1.0267752e-06, 9.9893409e-01, 1.1468343e-04, 8.7785593e-06,
        1.2244221e-05, 8.7833530e-07, 7.1156933e-06, 7.6877460e-04,
        1.5201580e-04, 2.8276065e-07],
       [9.9977726e-01, 4.2991285e-08, 1.2221230e-04, 4.1907714e-07,
        3.4494579e-07, 8.2956594e-06, 2.5809119e-05, 6.2876388e-05,
        8.9874135e-09, 2.7213975e-06],
       [1.7055314e-07, 6.1179146e-09, 4.0896898e-06, 4.4786209e-08,
        9.9668866e-01, 5.7737344e-07, 1.9357421e-06, 3.6610109e-05,
        1.3159632e-07, 3.2678444e-03]], dtype=float32)>

In [ ]:
# Congratulations! You have trained a machine learning model using a prebuilt dataset using the Keras API.
# For more examples of using Keras, check out the tutorials. To learn more about building models with Keras, read the guides.
# If you want learn more about loading and preparing data, see the tutorials on image data loading or CSV data loading.
