<a href="https://colab.research.google.com/github/Nikitaion/TensorFlowLearning/blob/main/11_tensorflow_exam_skills_checklist.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Skills checklist


# Проработать всё тут, а потом запустить тот же код в PyCharm с настройками под экзамен
Этот раздел удалить

##(1) TensorFlow developer skills

*   Know how to program in Python, resolve Python issues, and compile and run Python programs in PyCharm. ✅
*   Know how to find information about TensorFlow APIs, including how to find guides and API ✅
*   Know how to find information about TensorFlow APIs, including how to find guides and API references on tensorflow.org. ✅
*  Know how to debug, investigate, and solve error messages from the TensorFlow API. ✅
*  Know how to search beyond tensorflow.org, as and when necessary, to solve your TensorFlow questions. ✅
*  Know how to create ML models using TensorFlow where the model size is reasonable for the problem being solved. ✅
*  Know how to save ML models and check the model file size.
*  Understand the compatibility discrepancies between different versions of TensorFlow.

## (2) Building and training neural network models using TensorFlow 2.x


* Use TensorFlow 2.x. ✅
* Build, compile and train machine learning (ML) models using TensorFlow.
* Preprocess data to get it ready for use in a model.
* Use models to predict results.
* Build and train models for binary classification.
* Build and train models for multi-class categorization.
* Plot loss and accuracy of a trained model.
* Identify strategies to prevent overfitting, including augmentation and dropout.
* Use pretrained models (transfer learning).
* Extract features from pre-trained models.
* Ensure that inputs to a model are in the correct shape.
* Ensure that you can match test data to the input shape of a neural network
* Ensure you can match output data of a neural network to specified input shape for test data
* Understand batch loading of data.
* Use callbacks to trigger the end of training cycles.
* Use datasets from different sources.
* Use datasets in different formats, including json and csv
* Use datasets from tf.data.datasets.

In [2]:
import tensorflow as tf
print(f"Tensorflow version: {tf.__version__}")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import tensorflow_datasets as tfds


Tensorflow version: 2.8.0


In [3]:
# download dataset from tensorflow_datasets
ds = tfds.load('titanic', split='train')
ds

<PrefetchDataset element_spec={'features': {'age': TensorSpec(shape=(), dtype=tf.float32, name=None), 'boat': TensorSpec(shape=(), dtype=tf.string, name=None), 'body': TensorSpec(shape=(), dtype=tf.int32, name=None), 'cabin': TensorSpec(shape=(), dtype=tf.string, name=None), 'embarked': TensorSpec(shape=(), dtype=tf.int64, name=None), 'fare': TensorSpec(shape=(), dtype=tf.float32, name=None), 'home.dest': TensorSpec(shape=(), dtype=tf.string, name=None), 'name': TensorSpec(shape=(), dtype=tf.string, name=None), 'parch': TensorSpec(shape=(), dtype=tf.int32, name=None), 'pclass': TensorSpec(shape=(), dtype=tf.int64, name=None), 'sex': TensorSpec(shape=(), dtype=tf.int64, name=None), 'sibsp': TensorSpec(shape=(), dtype=tf.int32, name=None), 'ticket': TensorSpec(shape=(), dtype=tf.string, name=None)}, 'survived': TensorSpec(shape=(), dtype=tf.int64, name=None)}>

In [4]:
for x in ds:
  print(x)
  # for y in x:
  #   print(y)

# Словарь с ключами features (X) и survived (y). Нужно разделить на X/y

{'features': {'age': <tf.Tensor: shape=(), dtype=float32, numpy=30.0>, 'boat': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>, 'body': <tf.Tensor: shape=(), dtype=int32, numpy=-1>, 'cabin': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>, 'embarked': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'fare': <tf.Tensor: shape=(), dtype=float32, numpy=13.0>, 'home.dest': <tf.Tensor: shape=(), dtype=string, numpy=b'Sarnia, ON'>, 'name': <tf.Tensor: shape=(), dtype=string, numpy=b'McCrie, Mr. James Matthew'>, 'parch': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'pclass': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'sex': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'sibsp': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'ticket': <tf.Tensor: shape=(), dtype=string, numpy=b'233478'>}, 'survived': <tf.Tensor: shape=(), dtype=int64, numpy=0>}
{'features': {'age': <tf.Tensor: shape=(), dtype=float32, numpy=37.0>, 'boat': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>, 'body': <t

In [6]:
ds.shape

AttributeError: ignored

In [10]:
list(ds)

[{'features': {'age': <tf.Tensor: shape=(), dtype=float32, numpy=30.0>,
   'boat': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>,
   'body': <tf.Tensor: shape=(), dtype=int32, numpy=-1>,
   'cabin': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>,
   'embarked': <tf.Tensor: shape=(), dtype=int64, numpy=2>,
   'fare': <tf.Tensor: shape=(), dtype=float32, numpy=13.0>,
   'home.dest': <tf.Tensor: shape=(), dtype=string, numpy=b'Sarnia, ON'>,
   'name': <tf.Tensor: shape=(), dtype=string, numpy=b'McCrie, Mr. James Matthew'>,
   'parch': <tf.Tensor: shape=(), dtype=int32, numpy=0>,
   'pclass': <tf.Tensor: shape=(), dtype=int64, numpy=1>,
   'sex': <tf.Tensor: shape=(), dtype=int64, numpy=0>,
   'sibsp': <tf.Tensor: shape=(), dtype=int32, numpy=0>,
   'ticket': <tf.Tensor: shape=(), dtype=string, numpy=b'233478'>},
  'survived': <tf.Tensor: shape=(), dtype=int64, numpy=0>},
 {'features': {'age': <tf.Tensor: shape=(), dtype=float32, numpy=37.0>,
   'boat': <tf.Tensor: shape=(),

In [11]:
tf.data.Dataset.from_tensor_slices(list(ds))

ValueError: ignored

In [50]:
for example in ds:
  print(example)
  # print(example[1].numpy())
  exit()


{'features': {'age': <tf.Tensor: shape=(), dtype=float32, numpy=30.0>, 'boat': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>, 'body': <tf.Tensor: shape=(), dtype=int32, numpy=-1>, 'cabin': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>, 'embarked': <tf.Tensor: shape=(), dtype=int64, numpy=2>, 'fare': <tf.Tensor: shape=(), dtype=float32, numpy=13.0>, 'home.dest': <tf.Tensor: shape=(), dtype=string, numpy=b'Sarnia, ON'>, 'name': <tf.Tensor: shape=(), dtype=string, numpy=b'McCrie, Mr. James Matthew'>, 'parch': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'pclass': <tf.Tensor: shape=(), dtype=int64, numpy=1>, 'sex': <tf.Tensor: shape=(), dtype=int64, numpy=0>, 'sibsp': <tf.Tensor: shape=(), dtype=int32, numpy=0>, 'ticket': <tf.Tensor: shape=(), dtype=string, numpy=b'233478'>}, 'survived': <tf.Tensor: shape=(), dtype=int64, numpy=0>}
{'features': {'age': <tf.Tensor: shape=(), dtype=float32, numpy=37.0>, 'boat': <tf.Tensor: shape=(), dtype=string, numpy=b'Unknown'>, 'body': <t

In [ ]:
# Preprocess data to get it ready for use in a model.


In [ ]:
# Know how to save ML models and check the model file size.

# (3) Image classification


*   Define Convolutional neural networks with Conv2D and pooling layers.
*   Build and train models to process real-world image datasets.
*   Understand how to use convolutions to improve your neural network
*   Use real-world images in different shapes and sizes
*   Use image augmentation to prevent overfitting.
*   Use ImageDataGenerator.
*   Understand how ImageDataGenerator labels images based on the directory structure.


# (4) Natural language processing (NLP)


*   Build natural language processing systems using TensorFlow.
*   Prepare text to use in TensorFlow models.
*   Build models that identify the category of a piece of text using binary categorization
*   Build models that identify the category of a piece of text using multi-class categorization
*   Use word embeddings in your TensorFlow model.
*   Use LSTMs in your model to classify text for either binary or multi-class categorization.
*   Add RNN and GRU layers to your mode
*   Use RNNS, LSTMs, GRUs and CNNs in models that work with text.
*   Train LSTMs on existing text to generate text (such as songs and poetry) 


# (5) Time series, sequences and predictions


*   Train, tune and use time series, sequence and prediction models
*   Train models to predict values for both univariate and multivariate time series.
*   Prepare data for time series learning.
*   Understand Mean Absolute Error (MAE) and how it can be used to evaluate accuracy of sequence models.
*   Use RNNs and CNNs for time series, sequence and forecasting models
*   Identify when to use trailing versus centred windows
*   Use TensorFlow for forecasting
*   Prepare features and labels
*   Identify and compensate for sequence bias
*   Adjust the learning rate dynamically in time series, sequence and prediction models

## Troubleshooting tidbits


* **Input and output shapes** — print these out if you're stuck.
* **Input and output datatypes** — TensorFlow usually prefers float32.
* **Output activation functions** — for classification: `sigmoid` vs `softmax`, which one should you use?
* **Loss functions** — for classification `sparse_categorical_crossentropy` vs `categorical_crossentropy`, which one should you use?
* **Ways to improve a model** — if your model isn't performing as well as it should, what can you do?

Common ways to improve a deep model:
* Adding layers
* Increase the number of hidden units
* Change the activation functions
* Change the optimization funcion
* Change the learning rate
* Fitting on more data
* Fitting for longer

In [ ]:
# Save a model using the SavedModel format
model_name.save('name_for_file')

# Save a model using the HDF5 format
model_name.save("name_for_h5_file.h5") # note the addition of '.h5' on the end

# Load a model from the SavedModel format
loaded_saved_model = tf.keras.models.load_model("name_for_file")

# Load a model from the HDF5 format
loaded_h5_model = tf.keras.models.load_model("name_for_h5_file.h5")

loaded_saved_model.summary()
loaded_h5_model.summary()

In [ ]:
# Download saved model (or any file) from Google Colab
from google.colab import files
files.download("name_for_h5_file.h5")


## Preprocessing data (normalization and standardization)

A common practice when working with neural networks is to make sure all of the data you pass to them is in the range 0 to 1.

This practice is called **normalization** (scaling all values from their original range to, e.g. between 0 and 100,000 to be between 0 and 1).

There is another process call **standardization** which converts all of your data to unit variance and 0 mean.

These two practices are often part of a preprocessing pipeline (a series of functions to prepare your data for use with neural networks).

Knowing this, some of the major steps you'll take to preprocess your data for a neural network include:
* Turning all of your data to numbers (a neural network can't handle strings).
* Making sure your data is in the right shape (verifying input and output shapes).
* [**Feature scaling**](https://scikit-learn.org/stable/modules/preprocessing.html#preprocessing-scaler):
    * Normalizing data (making sure all values are between 0 and 1). This is done by subtracting the minimum value then dividing by the maximum value minus the minmum. This is also referred to as min-max scaling.
    * Standardization (making sure all values have a mean of 0 and a variance of 1). This is done by substracting the mean value from the target feature and then dividing it by the standard deviation.
    * Which one should you use?
      * **With neural networks you'll tend to favour normalization** as they tend to prefer values between 0 and 1 (you'll see this espcially with image processing), however, you'll often find a neural network can perform pretty well with minimal feature scaling.

> 📖 Resources for more on preprocessing data:
* [Scikit-Learn's documentation on preprocessing data](https://scikit-learn.org/stable/modules/preprocessing.html#preprocessing-data).
* [Scale, Standardize or Normalize with Scikit-Learn by Jeff Hale](https://towardsdatascience.com/scale-standardize-or-normalize-with-scikit-learn-6ccc7d176a02).

## Typical architecture of a regression neural network 

| **Hyperparameter** | **Typical value** |
| --- | --- |
| Input layer shape | Same shape as number of features (e.g. 3 for # bedrooms, # bathrooms, # car spaces in housing price prediction) |
| Hidden layer(s) | Problem specific, minimum = 1, maximum = unlimited |
| Neurons per hidden layer | Problem specific, generally 10 to 100 |
| Output layer shape | Same shape as desired prediction shape (e.g. 1 for house price) |
| Hidden activation | Usually [ReLU](https://www.kaggle.com/dansbecker/rectified-linear-units-relu-in-deep-learning) (rectified linear unit) |
| Output activation | None, ReLU, logistic/tanh |
| Loss function | [MSE](https://en.wikipedia.org/wiki/Mean_squared_error) (mean square error) or [MAE](https://en.wikipedia.org/wiki/Mean_absolute_error) (mean absolute error)/Huber (combination of MAE/MSE) if outliers |
| Optimizer | [SGD](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/SGD) (stochastic gradient descent), [Adam](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam) |

***Table 1:*** *Typical architecture of a regression network.*  ***Source:*** *Adapted from page 293 of [Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow Book by Aurélien Géron](https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/)*

## Typical architecture of a classification neural network 

| **Hyperparameter** | **Binary Classification** | **Multiclass classification** |
| --- | --- | --- |
| Input layer shape | Same as number of features (e.g. 5 for age, sex, height, weight, smoking status in heart disease prediction) | Same as binary classification |
| Hidden layer(s) | Problem specific, minimum = 1, maximum = unlimited | Same as binary classification |
| Neurons per hidden layer | Problem specific, generally 10 to 100 | Same as binary classification |
| Output layer shape | 1 (one class or the other) | 1 per class (e.g. 3 for food, person or dog photo) |
| Hidden activation | Usually [ReLU](https://www.kaggle.com/dansbecker/rectified-linear-units-relu-in-deep-learning) (rectified linear unit) | Same as binary classification |
| Output activation | [Sigmoid](https://en.wikipedia.org/wiki/Sigmoid_function) | [Softmax](https://en.wikipedia.org/wiki/Softmax_function) |
| Loss function | [Cross entropy](https://en.wikipedia.org/wiki/Cross_entropy#Cross-entropy_loss_function_and_logistic_regression) ([`tf.keras.losses.BinaryCrossentropy`](https://www.tensorflow.org/api_docs/python/tf/keras/losses/BinaryCrossentropy) in TensorFlow) | Cross entropy ([`tf.keras.losses.CategoricalCrossentropy`](https://www.tensorflow.org/api_docs/python/tf/keras/losses/CategoricalCrossentropy) in TensorFlow) |
| Optimizer | [SGD](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/SGD) (stochastic gradient descent), [Adam](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam) | Same as binary classification |

***Table 1:*** *Typical architecture of a classification network.* ***Source:*** *Adapted from page 295 of [Hands-On Machine Learning with Scikit-Learn, Keras & TensorFlow Book by Aurélien Géron](https://www.oreilly.com/library/view/hands-on-machine-learning/9781492032632/)*