<a href="https://colab.research.google.com/github/Nikitaion/TensorFlowLearning/blob/main/numpy_arrays_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://numpy.org/doc/stable/user/basics.indexing.html#basics-indexing

In [13]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
x[2]

2

In [4]:
x[-2]

8

In [7]:
x.shape = (2, 5)  # now x is 2-dimensional
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [8]:
x[1, 3]

8

In [9]:
x[0]

array([0, 1, 2, 3, 4])

In [10]:
x[0, 2]

2

In [11]:
x[0][2]

2

In [12]:
x[0, 2] == x[0][2]

True

So note that x[0, 2] == x[0][2] though the second case is more inefficient as a new temporary array is created after the first index that is subsequently indexed by 2.

