<a href="https://colab.research.google.com/github/Nikitaion/TensorFlowLearning/blob/main/sequential_model_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
X = np.array([-11.0, -3.0, -1.0, 2.0, 3.0, 6.0, 12.0, 14.0])
y = np.array([-1.0, 7.0, 9.0, 12.0, 13.0, 16.0, 22.0, 24.0])

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(50, activation="relu"),
    tf.keras.layers.Dense(1)
])
model

In [ ]:
model.layers

In [ ]:
model.compile(loss="mae",
              optimizer=tf.keras.optimizers.Adam(lr=0.1),
              metrics=["mae"])

/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


In [ ]:
model.fit(X, y, epochs = 50)

Epoch 1/50
1/1 [==============================] - 0s 362ms/step - loss: 14.3744 - mae: 14.3744
Epoch 2/50
1/1 [==============================] - 0s 5ms/step - loss: 11.2175 - mae: 11.2175
Epoch 3/50
1/1 [==============================] - 0s 6ms/step - loss: 5.5758 - mae: 5.5758
Epoch 4/50
1/1 [==============================] - 0s 7ms/step - loss: 6.5920 - mae: 6.5920
Epoch 5/50
1/1 [==============================] - 0s 6ms/step - loss: 8.1660 - mae: 8.1660
Epoch 6/50
1/1 [==============================] - 0s 7ms/step - loss: 7.8472 - mae: 7.8472
Epoch 7/50
1/1 [==============================] - 0s 11ms/step - loss: 6.3127 - mae: 6.3127
Epoch 8/50
1/1 [==============================] - 0s 6ms/step - loss: 4.4730 - mae: 4.4730
Epoch 9/50
1/1 [==============================] - 0s 11ms/step - loss: 4.3665 - mae: 4.3665
Epoch 10/50
1/1 [==============================] - 0s 9ms/step - loss: 4.0407 - mae: 4.0407
Epoch 11/50
1/1 [==============================] - 0s 14ms/step - loss: 2.6399 - 

In [ ]:
model.weights

[<tf.Variable 'dense_16/kernel:0' shape=(1, 50) dtype=float32, numpy=
 array([[-0.0740361 , -0.3295938 ,  0.26678082,  0.07655781,  0.09126662,
          0.07137948, -0.07038241,  0.21027626,  0.14219707,  0.13003702,
          0.07168192, -0.23395728, -0.01148269, -0.01578076, -0.33280706,
         -0.01861232, -0.27988327, -0.36691365, -0.30890405,  0.22599967,
         -0.03029022,  0.2757822 , -0.1902074 ,  0.08240667,  0.01574371,
          0.22042653, -0.15118586, -0.08909077,  0.04835643,  0.21653296,
         -0.05176051, -0.16407754, -0.08743519, -0.2767273 , -0.2878847 ,
         -0.05452538, -0.2916206 , -0.2788831 ,  0.10576811, -0.20938343,
          0.2087771 ,  0.07698931,  0.2966823 ,  0.02179689,  0.03185138,
          0.1118364 ,  0.02854629, -0.11176577, -0.24878353,  0.15132768]],
       dtype=float32)>,
 <tf.Variable 'dense_16/bias:0' shape=(50,) dtype=float32, numpy=
 array([ 0.0704262 , -1.0882988 ,  1.4007308 , -1.5869466 , -1.6006784 ,
        -0.9092979 , -1.0

In [ ]:
model.summary()

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_16 (Dense)             (None, 50)                100       
_________________________________________________________________
dense_17 (Dense)             (None, 1)                 51        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


### New model

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(10, activation="relu"),
    tf.keras.layers.Dense(1)
])
model.compile(loss="mae",
              optimizer=tf.keras.optimizers.Adam(lr=0.1),
              metrics=["mae"])
model.fit(X, y, epochs = 50)

Epoch 1/50


/usr/local/lib/python3.7/dist-packages/keras/optimizer_v2/optimizer_v2.py:356: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  "The `lr` argument is deprecated, use `learning_rate` instead.")


1/1 [==============================] - 1s 618ms/step - loss: 9.9972 - mae: 9.9972
Epoch 2/50
1/1 [==============================] - 0s 6ms/step - loss: 7.3914 - mae: 7.3914
Epoch 3/50
1/1 [==============================] - 0s 6ms/step - loss: 4.7412 - mae: 4.7412
Epoch 4/50
1/1 [==============================] - 0s 6ms/step - loss: 6.9446 - mae: 6.9446
Epoch 5/50
1/1 [==============================] - 0s 7ms/step - loss: 6.5141 - mae: 6.5141
Epoch 6/50
1/1 [==============================] - 0s 6ms/step - loss: 3.6622 - mae: 3.6622
Epoch 7/50
1/1 [==============================] - 0s 5ms/step - loss: 5.5500 - mae: 5.5500
Epoch 8/50
1/1 [==============================] - 0s 5ms/step - loss: 6.4275 - mae: 6.4275
Epoch 9/50
1/1 [==============================] - 0s 7ms/step - loss: 3.2749 - mae: 3.2749
Epoch 10/50
1/1 [==============================] - 0s 5ms/step - loss: 2.3085 - mae: 2.3085
Epoch 11/50
1/1 [==============================] - 0s 5ms/step - loss: 2.7462 - mae: 2.7462
Epoch 

In [ ]:
model.weights

[<tf.Variable 'dense_18/kernel:0' shape=(1, 10) dtype=float32, numpy=
 array([[ 0.34147537,  0.37533614,  0.18453509, -0.2875632 ,  0.13523847,
         -0.24109425, -0.11799396,  0.23314174,  0.01138617, -0.44685438]],
       dtype=float32)>,
 <tf.Variable 'dense_18/bias:0' shape=(10,) dtype=float32, numpy=
 array([ 0.6772456 ,  0.2795054 ,  0.64602387, -0.9231858 ,  0.58684444,
        -1.0196624 ,  0.60016245,  0.4957213 , -1.5944146 , -0.8187692 ],
       dtype=float32)>,
 <tf.Variable 'dense_19/kernel:0' shape=(10, 10) dtype=float32, numpy=
 array([[ 0.40466177,  0.19539528,  0.14525531,  0.5351108 , -0.06071511,
         -1.1857073 ,  0.40487933, -0.6117156 ,  0.61241055, -0.2540742 ],
        [ 0.06657708,  0.07166089,  0.41969055, -0.30784848, -0.9006319 ,
         -0.25710484, -0.388122  , -0.8126345 ,  0.5623902 , -0.20475422],
        [ 0.31467518,  0.05506584,  0.03252618,  0.46137097, -0.14979057,
         -1.4833337 , -0.0895395 , -0.33680978,  0.20065564, -0.5994593 ],
 

In [ ]:
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_18 (Dense)             (None, 10)                20        
_________________________________________________________________
dense_19 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_20 (Dense)             (None, 10)                110       
_________________________________________________________________
dense_21 (Dense)             (None, 1)                 11        
Total params: 251
Trainable params: 251
Non-trainable params: 0
_________________________________________________________________
