<a href="https://colab.research.google.com/github/Nikitaion/TensorFlowLearning/blob/main/numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [45]:
import numpy as np

## DaraTypes & Attributes

In [46]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [47]:
type(a1)

numpy.ndarray

In [48]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12],
                [13, 14, 15],
                [16, 17, 18]]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [49]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [50]:
a1.shape, a2.shape, a3.shape

((3,), (2, 3), (2, 3, 3))

In [51]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [52]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [53]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [54]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [55]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## 2. Creating arrays

In [56]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [57]:
sample_array.dtype

dtype('int64')

In [58]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [59]:
ones.dtype

dtype('float64')

In [60]:
type(ones)

numpy.ndarray

In [61]:
zeros = np.zeros((2, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [63]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[9, 3, 9, 0, 7],
       [6, 4, 7, 0, 9],
       [3, 2, 2, 2, 7]])

In [64]:
random_array.size

15

In [65]:
random_array.shape

(3, 5)

In [66]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.68825984, 0.95376952, 0.09158059],
       [0.15514579, 0.75334585, 0.49215585],
       [0.09284121, 0.01842004, 0.85745692],
       [0.13282502, 0.93193525, 0.39467101],
       [0.44771369, 0.33128456, 0.68201011]])

In [67]:
random_array_2.shape

(5, 3)

In [68]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.21313474, 0.6553308 , 0.79242547],
       [0.05867867, 0.38939253, 0.1501167 ],
       [0.20227402, 0.65501326, 0.46487098],
       [0.22041079, 0.70391166, 0.76862255],
       [0.034474  , 0.32917239, 0.10981551]])

In [76]:
# Pseudo random numbers
np.random.seed(seed=10)

random_array_4 = np.random.randint(10, size = (5, 3)) # (from 0 to 9 with specified size)
random_array_4

array([[9, 4, 0],
       [1, 9, 0],
       [1, 8, 9],
       [0, 8, 6],
       [4, 3, 0]])

## 3. Viewing arrays and matrices

In [77]:
np.unique(random_array_4) # find unique elements in array

array([0, 1, 3, 4, 6, 8, 9])

In [78]:
a1

array([1, 2, 3])

In [79]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [80]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [81]:
a1[0]

1

In [82]:
a2.shape

(2, 3)

In [85]:
a2[0]

array([1. , 2. , 3.3])

In [86]:
a3.shape

(2, 3, 3)

In [84]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [89]:
a2[1]

array([4. , 5. , 6.5])

In [90]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [88]:
a3[:2, :2, :2] # Get fiest 3 values of each shape (row, column, array)

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [96]:
np.random.seed(42)
a4 = np.random.randint(10, size = (2, 3, 4, 5))
a4

array([[[[6, 3, 7, 4, 6],
         [9, 2, 6, 7, 4],
         [3, 7, 7, 2, 5],
         [4, 1, 7, 5, 1]],

        [[4, 0, 9, 5, 8],
         [0, 9, 2, 6, 3],
         [8, 2, 4, 2, 6],
         [4, 8, 6, 1, 3]],

        [[8, 1, 9, 8, 9],
         [4, 1, 3, 6, 7],
         [2, 0, 3, 1, 7],
         [3, 1, 5, 5, 9]]],


       [[[3, 5, 1, 9, 1],
         [9, 3, 7, 6, 8],
         [7, 4, 1, 4, 7],
         [9, 8, 8, 0, 8]],

        [[6, 8, 7, 0, 7],
         [7, 2, 0, 7, 2],
         [2, 0, 4, 9, 6],
         [9, 8, 6, 8, 7]],

        [[1, 0, 6, 6, 7],
         [4, 2, 7, 5, 2],
         [0, 2, 4, 2, 0],
         [4, 9, 6, 6, 8]]]])

In [103]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [108]:
# Вывести первые 4 числа каждого измерения
a4[:, :, :, :4]

array([[[[6, 3, 7, 4],
         [9, 2, 6, 7],
         [3, 7, 7, 2],
         [4, 1, 7, 5]],

        [[4, 0, 9, 5],
         [0, 9, 2, 6],
         [8, 2, 4, 2],
         [4, 8, 6, 1]],

        [[8, 1, 9, 8],
         [4, 1, 3, 6],
         [2, 0, 3, 1],
         [3, 1, 5, 5]]],


       [[[3, 5, 1, 9],
         [9, 3, 7, 6],
         [7, 4, 1, 4],
         [9, 8, 8, 0]],

        [[6, 8, 7, 0],
         [7, 2, 0, 7],
         [2, 0, 4, 9],
         [9, 8, 6, 8]],

        [[1, 0, 6, 6],
         [4, 2, 7, 5],
         [0, 2, 4, 2],
         [4, 9, 6, 6]]]])

In [107]:
# Вывести 3, 5, 1, 9 (2, 1, 1, 1-4) из a4
a4[-1:, :1, :1, :4]

array([[[[3, 5, 1, 9]]]])

## 4. Manipulating & comparing arrays

### Arithmetic

In [109]:
a1

array([1, 2, 3])

In [111]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [112]:
a1 + ones

array([2., 3., 4.])

In [113]:
a1 - ones

array([0., 1., 2.])

In [114]:
a1 * ones

array([1., 2., 3.])

In [115]:
a1 / ones

array([1., 2., 3.])

In [120]:
a1

array([1, 2, 3])

In [119]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [117]:
a1 * a2

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [121]:
a1 + a2

array([[2. , 4. , 6.3],
       [5. , 7. , 9.5]])

In [122]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [133]:
a2 * a3
# ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

ValueError: ignored

In [134]:
# How reshape a2 to be compatible with a3
# Search: "How to reshape numpy array"
np.expand_dims(a2, axis=-1) * a3

array([[[  1. ,   2. ,   3. ],
        [  8. ,  10. ,  12. ],
        [ 23.1,  26.4,  29.7]],

       [[ 40. ,  44. ,  48. ],
        [ 65. ,  70. ,  75. ],
        [104. , 110.5, 117. ]]])

In [136]:
a2.shape, np.expand_dims(a2, axis=-1).shape

((2, 3), (2, 3, 1))

In [139]:
a2 / a1

array([[1.        , 1.        , 1.1       ],
       [4.        , 2.5       , 2.16666667]])

In [138]:
# Floor division removes the decimals (деление без остатка)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [140]:
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [141]:
np.square(a2) # like a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [142]:
np.add(a1, ones) # like a1 + ones

array([2., 3., 4.])

In [143]:
a1 % 2 # получить остаток

array([1, 0, 1])

In [144]:
a1 / 2

array([0.5, 1. , 1.5])

In [147]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [148]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

### Aggregation

Aggregation = performing the same operation on a number of things

In [149]:
listy_list = [1, 2, 3]
type(listy_list)

list

In [150]:
sum(listy_list)

6

In [151]:
sum(a1)

6

In [152]:
np.sum(a1)

6

 Use Python's methods (sum()) datatypes and use NumPy arrays (np.sum())

In [164]:
# Creative a massiv NumPy array
massive_array = np.random.random(100000)
massive_array.size

100000

In [165]:
massive_array[:10]

array([0.49640472, 0.76795097, 0.9660503 , 0.0085781 , 0.71768654,
       0.55992007, 0.24824405, 0.14838524, 0.10499097, 0.62057573])

In [166]:
%timeit sum(massive_array) # Python sum()
%timeit np.sum(massive_array) # NumPy sum()

# Numpy a lot of faster

100 loops, best of 5: 8.48 ms per loop
The slowest run took 4.11 times longer than the fastest. This could mean that an intermediate result is being cached.
10000 loops, best of 5: 40.3 µs per loop


In [167]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [168]:
np.mean(a2)

3.6333333333333333

In [169]:
np.max(a2)

6.5

In [174]:
np.min(a2)

1.0

In [175]:
# Standard deviation = a measure of how spread out a group of numbers is from the mean
np.std(a2)

1.8226964152656422

In [176]:
# Variacnce = measure of the average degree to which each number is different to the mean
# Higher variance = wider range of numbers
# Lower variance = lower range of numbers
np.var(a2)

3.3222222222222224

In [177]:
# Standard deviation = squareroot of variance
np.sqrt(np.var(a2)) 

1.8226964152656422