<a href="https://colab.research.google.com/github/Nikitaion/TensorFlowLearning/blob/main/numpy/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
array1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
array2 = np.array([[1, 2, 3],
                  [4, 5, 6]])

# Create a 3-dimensional Numpy array using np.array()
array3 = np.array([[[1, 2, 3],
                  [4, 5, 6]],
                  [[11, 12, 13],
                  [14, 15, 16]]])

In [6]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)

array1.shape, array1.ndim, array1.dtype, array1.size, type(array1)

((3,), 1, dtype('int64'), 3, numpy.ndarray)

In [7]:
# Attributes of 2-dimensional array
array2.shape, array2.ndim, array2.dtype, array2.size, type(array2)

((2, 3), 2, dtype('int64'), 6, numpy.ndarray)

In [8]:
# Attributes of 3-dimensional array
array3.shape, array3.ndim, array3.dtype, array3.size, type(array3)

((2, 2, 3), 3, dtype('int64'), 12, numpy.ndarray)

In [12]:
# Import pandas and create a DataFrame out of one of the arrays you've created
import pandas as pd
array1DF = pd.DataFrame(array1)
array1DF

0
0  1
1  2
2  3

In [13]:
array2DF = pd.DataFrame(array2)
array2DF

0  1  2
0  1  2  3
1  4  5  6

In [15]:
# Create an array of shape (10, 2) with only ones
array4 = np.ones((10, 2))
array4, array4.shape

(array([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]), (10, 2))

In [16]:
# Create an array of shape (7, 2, 3) of only zeros
array5 = np.zeros((7, 2, 3))
array5, array5.shape

(array([[[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]],
 
        [[0., 0., 0.],
         [0., 0., 0.]]]), (7, 2, 3))

In [19]:
# Create an array within a range of 0 and 100 with step 3
array6 = np.arange(0, 100, 3)
array6, array6.size

(array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
        51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]),
 34)

In [26]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array7 = np.random.randint(0, 10, size=(7,2))
array7, array7.dtype, array7.shape

(array([[5, 9],
        [0, 0],
        [5, 0],
        [7, 9],
        [3, 9],
        [1, 9],
        [1, 0]]), dtype('int64'), (7, 2))

In [27]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array8 = np.random.random((3, 5))
array8, array8.dtype, array8.shape

(array([[0.09669934, 0.69351927, 0.12271985, 0.65200672, 0.70085182],
        [0.17532964, 0.98914758, 0.17295462, 0.55002162, 0.4355327 ],
        [0.79452857, 0.63458921, 0.33786121, 0.38709948, 0.20547219]]),
 dtype('float64'),
 (3, 5))

In [33]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
array9 = np.random.random((4,6))
array9

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848, 0.15601864,
        0.15599452],
       [0.05808361, 0.86617615, 0.60111501, 0.70807258, 0.02058449,
        0.96990985],
       [0.83244264, 0.21233911, 0.18182497, 0.18340451, 0.30424224,
        0.52475643],
       [0.43194502, 0.29122914, 0.61185289, 0.13949386, 0.29214465,
        0.36636184]])

In [40]:
# Create an array of random numbers between 1 & 10 of size (3, 7) and save it to a variable
array10 = np.random.randint(1, 10, size=(3,7))

# Find the unique numbers in the array you just created
array10, np.unique(array10)

(array([[7, 2, 3, 1, 5, 1, 8],
        [1, 1, 2, 2, 6, 7, 5],
        [1, 1, 3, 2, 5, 6, 7]]), array([1, 2, 3, 5, 6, 7, 8]))

In [41]:
# Find the 0'th index of the latest array you created
array10[0]

array([7, 2, 3, 1, 5, 1, 8])

In [42]:
# Get the first 2 rows of latest array you created
array10[:2]

array([[7, 2, 3, 1, 5, 1, 8],
       [1, 1, 2, 2, 6, 7, 5]])

In [43]:
# Get the first 2 values of the first 2 rows of the latest array
array10[:2, :2]

array([[7, 2],
       [1, 1]])

In [44]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
array11 = np.random.randint(0, 10, size=(3, 5))
array12 = np.ones((3,5))
array11, array12

(array([[3, 6, 7, 0, 5],
        [7, 4, 3, 1, 5],
        [5, 0, 8, 5, 2]]), array([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]))

In [45]:
# Add the two arrays together
array11 + array12

array([[4., 7., 8., 1., 6.],
       [8., 5., 4., 2., 6.],
       [6., 1., 9., 6., 3.]])

In [46]:
# Create another array of ones of shape (5, 3)
array13 = np.ones((5,3))
array13

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [47]:
# Try add the array of ones and the other most recent array together
array12 + array13

# array12.T + array13

ValueError: ignored

In [53]:
# Create another array of ones of shape (3, 5)
array14 = np.ones((3,5))
# Subtract the new array of ones from the other most recent array
array11 - array14

array([[ 2.,  5.,  6., -1.,  4.],
       [ 6.,  3.,  2.,  0.,  4.],
       [ 4., -1.,  7.,  4.,  1.]])

In [54]:
# Multiply the ones array with the latest array
array11 * array14

array([[3., 6., 7., 0., 5.],
       [7., 4., 3., 1., 5.],
       [5., 0., 8., 5., 2.]])

In [57]:
# Take the latest array to the power of 2 using '**'
array11 ** 2

array([[ 9, 36, 49,  0, 25],
       [49, 16,  9,  1, 25],
       [25,  0, 64, 25,  4]])

In [58]:
# Do the same thing with np.square()
np.square(array11)

array([[ 9, 36, 49,  0, 25],
       [49, 16,  9,  1, 25],
       [25,  0, 64, 25,  4]])

In [59]:
# Find the mean of the latest array using np.mean()
np.mean(array11)

4.066666666666666

In [60]:
# Find the maximum of the latest array using np.max()
np.max(array11)

8

In [61]:
# Find the minimum of the latest array using np.min()
np.min(array11)

0

In [62]:
# Find the standard deviation of the latest array
np.std(array11)

2.434930982366623

In [63]:
# Find the variance of the latest array
np.var(array11)

5.928888888888889

In [64]:
# Reshape the latest array to (3, 5, 1)
array11.reshape((3,5,1))

array([[[3],
        [6],
        [7],
        [0],
        [5]],

       [[7],
        [4],
        [3],
        [1],
        [5]],

       [[5],
        [0],
        [8],
        [5],
        [2]]])

In [68]:
# Transpose the latest array
array11.T

array([[3, 7, 5],
       [6, 4, 0],
       [7, 3, 8],
       [0, 1, 5],
       [5, 5, 2]])

In [69]:
array11

array([[3, 6, 7, 0, 5],
       [7, 4, 3, 1, 5],
       [5, 0, 8, 5, 2]])

In [70]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
array15 = np.random.randint(0, 10, (3,3))
array16 = np.random.randint(0, 10, (3,2))

In [71]:
# Perform a dot product on the two newest arrays you created
array15.dot(array16)

array([[47, 32],
       [88, 26],
       [69, 57]])

In [72]:
np.dot(array15, array16)

array([[47, 32],
       [88, 26],
       [69, 57]])

In [75]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
array17 = np.random.randint(0, 10, (4,3))
array18 = np.random.randint(0, 10, (4,3))

In [76]:
# Perform a dot product on the two newest arrays you created
np.dot(array17, array18)

ValueError: ignored

In [85]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(array17, array18.T)

array([[ 32, 112,  32,  80],
       [ 37, 112,  38,  83],
       [ 38, 116,  46,  85],
       [  8,  50,  70,  25]])

In [82]:
# Compare the two arrays with '>'
array17 > array18

array([[False,  True,  True],
       [False, False,  True],
       [False,  True,  True],
       [ True, False, False]])

In [83]:
# Compare the two arrays with '>='
array17 >= array18

array([[False,  True,  True],
       [False,  True,  True],
       [False,  True,  True],
       [ True,  True, False]])

In [84]:
# Find which elements of the first array are greater than 7
array17 > 7

array([[False,  True,  True],
       [False, False,  True],
       [False, False,  True],
       [ True, False, False]])

In [94]:
# Which parts of each array are equal? (try using '==')
array17 == array18

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False,  True, False]])

In [95]:
array17

array([[0, 8, 8],
       [1, 6, 9],
       [2, 6, 9],
       [8, 3, 0]])

In [90]:
# Sort one of the arrays you just created in ascending order
np.sort(array17)

array([[0, 8, 8],
       [1, 6, 9],
       [2, 6, 9],
       [0, 3, 8]])

In [96]:
# Sort the indexes of one of the arrays you just created
np.argsort(array17)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [99]:
array18

array([[1, 0, 4],
       [4, 6, 8],
       [8, 2, 2],
       [2, 3, 7]])

In [101]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(array18)

5

In [102]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(array18)

1

In [103]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(array18, axis=1)

array([2, 2, 0, 2])

In [104]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(array18, axis=0)

array([0, 0, 2])

In [117]:
# Create an array of normally distributed random numbers
np.random.randn(2, 3, 4)

array([[[ 1.67374816,  0.04370267,  1.07368201,  0.07604804],
        [ 0.35295998,  0.61610665, -0.52872399, -1.28029113],
        [-1.30160333,  0.05084257, -0.48864009, -2.14585676]],

       [[ 0.51294125, -1.21848964, -1.16032503, -0.04162603],
        [-0.90011566,  0.1225055 ,  1.97346089, -0.37905765],
        [-1.05957915,  0.18150698, -0.77523179,  0.02375148]]])

In [119]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1, 100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])